name: Test

on:
  workflow_dispatch:
    inputs:
      notion_integration_secret:
        description: "Integration secret of notion"
        required: true
      parent_database_id:
        description: "Notion database ID to add release note"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish Release Note
      uses: "./"
      with:
        notion_integration_secret: ${{ secrets.SAMPLE_NOTION_INTEGRATION_SECRET }}
        parent_database_id: ${{ env.SAMPLE_NOTION_DATABASE_ID }}
        properties: |
          名前:
            title:
              - text:
                  content: ${{ github.repository }}
        github_ref_name: "0.0.0-sample"
