name: Test

on:
  workflow_dispatch:

env:
  # Use github.ref_name for publish events
  REF_NAME: "0.0.0-test"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Release Note
        uses: "./"
        with:
          notion_integration_secret: ${{ secrets.SAMPLE_NOTION_INTEGRATION_SECRET }}
          parent_database_id: ${{ vars.SAMPLE_NOTION_DATABASE_ID }}
          properties: |
            名前:
              title:
                - text:
                    content: "${{ env.REF_NAME }}"
            "GitHub Release":
              url: "https://github.com/utisam/github-release-notion/releases/tag/${{ env.REF_NAME }}"
          github_ref_name: "${{ env.REF_NAME }}"
